spring:
  profiles:
    active: init
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
#    Mybatis JdbcTemplate sql log
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    hello.itemservice.repository.mybatis: trace
#    org.springframework.jdbc: debug
